name: Ubuntu Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull tu_usuario/tu_imagen:tu_tag

      - name: Install xrdp and configure for root
        run: |
          # Instala xrdp y realiza la configuración para root
          sudo apt-get update
          sudo apt-get install -y xrdp
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
          echo 'root:admin' | sudo chpasswd

      - name: Install ngrok
        run: |
          # Instala ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          mv ngrok /usr/local/bin/

      - name: Start ngrok TCP tunnel
        run: |
          # Recupera el token de autenticación de ngrok desde los secretos de GitHub
          NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok authtoken $NGROK_AUTH_TOKEN
          ngrok tcp --region eu 3389 &

          # Espera unos segundos para asegurarse de que ngrok esté en funcionamiento
          sleep 5

          # Obtiene la dirección IP pública proporcionada por ngrok
          public_ip=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')

          # Muestra la dirección IP pública
          echo "Public IP Address: $public_ip"

      - name: Run Docker container
        run: |
          docker run -d albertlnz/laravel:latest

      - name: Keep Alive
        run: |
          # Añade un comando de larga duración para mantener viva la ejecución del flujo de trabajo
          while true; do
            echo "Workflow is running..."
            sleep 5184000  # Duerme durante 1 hora
          done
