name: Ubuntu Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull albertlnz/laravel:latest

      - name: Install xrdp and configure for root
        run: |
          # Install xrdp and configure for root
          sudo apt-get update
          sudo apt-get install -y xrdp
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
          echo 'root:admin' | sudo chpasswd

      - name: Install ngrok
        run: |
          # Install ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          mv ngrok /usr/local/bin/

      - name: Start ngrok TCP tunnel
        run: |
          # Retrieve ngrok authentication token from GitHub secrets
          NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok authtoken $NGROK_AUTH_TOKEN

          # Start ngrok with port 8000 (your application's port) in the EU region
          ngrok http --region eu 8000 &

          # Wait for a few seconds to ensure ngrok is running
          sleep 5

          # Get the public URL provided by ngrok
          public_url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')

          # Output the public URL
          echo "Public URL: $public_url"

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 albertlnz/laravel:latest

      - name: Keep Alive
        run: |
          # Add a long-running command to keep the workflow alive
          while true; do
            echo "Workflow is running..."
            sleep 5184000  # Sleep for 1 hour
          done
